[package]
name = "dgsp"
version = "0.1.0"
edition = "2021"

[dependencies]
pqcrypto-sphincsplus = { version = "0.7.0", features = ["serialization"] }
serde = { version = "1.0.215", features = ["derive"] }
bincode = "1.3"
thiserror = "2.0.3"
#base64 = "0.22.1"
#hex = "0.4.3"
#log = "0.4.22"
#bincode = "1.3.1"
#rand = "0.9.0-beta.1"
rand = { version = "0.8.5", features = ["std"] }
zeroize = {version = "1.8.1", features = ["zeroize_derive"]}
#serde_yaml = "0.9.34+deprecated"
pqcrypto-traits = "0.3.5"
#blake2-rfc = "0.2.18"
paste = "1.0" # used for identifiers concatenation
