name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      RUST_BACKTRACE: 1
    strategy:
      fail-fast: false
      matrix:
        sphincs: [
          sphincs_sha2_128f,
          sphincs_sha2_128s,
          sphincs_sha2_192f,
          sphincs_sha2_192s,
          sphincs_sha2_256f,
          sphincs_sha2_256s,
          sphincs_shake_128f,
          sphincs_shake_128s,
          sphincs_shake_192f,
          sphincs_shake_192s,
          sphincs_shake_256f,
          sphincs_shake_256s
        ]
        storage: [ in-disk, in-memory ]

    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: cargo build --no-default-features --features "${{ matrix.sphincs }} ${{ matrix.storage }}" --verbose

      - name: Run tests
        run: cargo test --no-default-features --features "${{ matrix.sphincs }} ${{ matrix.storage }}" --verbose
